[package]
name = "nish"
description = "Jump into flake-based nix shells with ease"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
runix = "0.1.1"
tokio = { version = "1", features = ["full"] }
